global using System.Windows;

global using ICSharpCode.ILSpy.Commands;
global using ICSharpCode.ILSpy.Util;
global using ICSharpCode.ILSpy.Docking;

global using Avalonia.Labs.Input;
global using Avalonia.Controls;
global using Avalonia.Data;
global using ImageSource = Avalonia.Media.Imaging.Bitmap;
global using IHighlightingDefinition = AvaloniaEdit.Highlighting.IHighlightingDefinition;
global using HighlightingColor = AvaloniaEdit.Highlighting.HighlightingColor;
global using HighlightingManager = AvaloniaEdit.Highlighting.HighlightingManager;
global using Window = Avalonia.Controls.Window;
global using RoutedEventArgs = Avalonia.Interactivity.RoutedEventArgs;
global using Key = Avalonia.Input.Key;
global using ModifierKeys = Avalonia.Input.KeyModifiers;
global using App = ProjectRover.App;
global using WindowState = Avalonia.Controls.WindowState;
global using Colors = Avalonia.Media.Colors;
global using Color = Avalonia.Media.Color;
global using KeyGesture = Avalonia.Input.KeyGesture;
global using FontWeight = Avalonia.Media.FontWeight;
global using SimpleHighlightingBrush = AvaloniaEdit.Highlighting.SimpleHighlightingBrush;
global using RichText = AvaloniaEdit.Highlighting.RichText;
global using OpenFolderDialog = Microsoft.Win32.OpenFolderDialog;
global using SaveFileDialog = Microsoft.Win32.SaveFileDialog;
global using OpenFileDialog = Microsoft.Win32.OpenFileDialog;
global using Thickness = Avalonia.Thickness;
global using Orientation = Avalonia.Layout.Orientation;
global using RichTextModel = AvaloniaEdit.Highlighting.RichTextModel;
global using DocumentHighlighter = AvaloniaEdit.Highlighting.DocumentHighlighter;
global using IDocument = AvaloniaEdit.Document.IDocument;
global using UIElement = Avalonia.Controls.Control;
global using Rect = Avalonia.Rect;